### ISSUE TITLE
About version package

### ISSUE THREAD

**Issue by ThanhPham1987** [Madhubalajb/Self-Attendance-System#1]
Hi Madhubalajb,
Can you tell me which python version are you using for this code?
Best regards,
PeterPham

**Comment by avinashkoshal** [comment]
I have cloned the repo and tested it on my system having Python 3.6 and it worked perfectly
so I guess Python3 is the version

**Comment by Madhubalajb** [comment]
as @aaavinash85 said, I have used Python3 (Python 3.6) version.
