### ISSUE TITLE
IDE

### ISSUE THREAD

**Issue by lllflpj** [Madhubalajb/Self-Attendance-System#2]
Excuse me, what IDE are you using?

**Comment by Madhubalajb** [comment]
I didn't use any particular IDE. 
FYI I have used **Python Command Prompt** and [Atom Editor](https://atom.io/).

**Comment by lllflpj** [comment]
well,thank you for your reply.

------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Madhubala"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月11日(星期一) 上午10:51
收件人:&nbsp;"Madhubalajb/FaceNet-based-Attendance-System"<FaceNet-based-Attendance-System@noreply.github.com&gt;;
抄送:&nbsp;"。"<277875526@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Madhubalajb/FaceNet-based-Attendance-System] IDE (#2)





 
I didn't use any particular IDE.
 FYI I have used Python Command Prompt and Atom Editor.
